#Application URL

app_URL=https://practicetestautomation.com/practice-test-login/
app_URL_stg=https://practicetestautomation.com/practice-test-login/



#TestData
username=student
password=Password123



#Locators
username_id=username
password_id=password
login_id=submit
Login_Successfully_text_xpath=//*[@id='loop-container']/div/article/div[2]/p[1]/strong